# Generated by Django 3.1.2 on 2020-12-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201223_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='strava',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
