# Generated by Django 3.1.2 on 2020-10-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
