# Generated by Django 3.1.2 on 2020-10-30 17:20

from django.db import migrations
#import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201030_1705'),
    ]

    #operations = [
     #   migrations.AlterField(
      #      model_name='post',
       #     name='body',
            #field=django_quill.fields.QuillField(blank=True, null=True),
        #),
    #]
