# Generated by Django 3.1.2 on 2020-12-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201223_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='post',
            name='polyline',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='strava',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='link_shoe',
            field=models.CharField(max_length=255),
        ),
    ]
