# Generated by Django 3.1.2 on 2020-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201223_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='polyline',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
