# Generated by Django 3.1.2 on 2020-10-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201030_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Open for your next adventure', max_length=255),
        ),
    ]
