# Generated by Django 3.1.2 on 2020-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201223_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='ankle_stabilization',
            field=models.CharField(default='60', max_length=255),
        ),
        migrations.AddField(
            model_name='shoe',
            name='breathability',
            field=models.CharField(default='60', max_length=255),
        ),
        migrations.AddField(
            model_name='shoe',
            name='isolation',
            field=models.CharField(default='60', max_length=255),
        ),
        migrations.AddField(
            model_name='shoe',
            name='sole_stiffness',
            field=models.CharField(default='60', max_length=255),
        ),
        migrations.AddField(
            model_name='shoe',
            name='water_resistance',
            field=models.CharField(default='60', max_length=255),
        ),
    ]
