# Generated by Django 3.1.2 on 2020-12-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201224_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='ankle_stabilization',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='breathability',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='isolation',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='sole_stiffness',
            field=models.IntegerField(blank=True, default=60),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='water_resistance',
            field=models.IntegerField(blank=True, default=60),
        ),
    ]
