# Generated by Django 3.1.2 on 2020-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201031_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='strava',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
