# Generated by Django 3.1.2 on 2020-12-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_strava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='strava',
            field=models.IntegerField(default=0),
        ),
    ]
