# Generated by Django 3.1.2 on 2020-12-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201218_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
    ]
