# Generated by Django 3.1.2 on 2020-12-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20201218_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='polyline',
            field=models.CharField(default=0, max_length=2048),
        ),
    ]
