# Generated by Django 3.1.2 on 2020-12-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_polyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='polyline',
            field=models.CharField(default=0, max_length=100000),
        ),
    ]
