# Generated by Django 3.1.2 on 2020-12-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201219_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddShoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(max_length=255)),
                ('link_picture', models.CharField(max_length=255)),
            ],
        ),
    ]
