# Generated by Django 3.1.2 on 2020-12-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_addshoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='addshoe',
            name='link_shoe',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
