# Generated by Django 3.1.2 on 2020-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shoes',
            field=models.ManyToManyField(to='blog.AddShoe'),
        ),
    ]
